# Generated by Django 5.2.15 on 2026-09-18 03:06

import sxdevops.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multicloud', '0002_rename_business_line_verbose_to_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudcredential',
            name='access_key_secret',
            field=sxdevops.fields.EncryptedCharField(blank=True, default='', max_length=255, verbose_name='Access Key Secret'),
        ),
    ]
