# Generated by Django 5.2.15 on 2026-07-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0021_remove_aiopsknowledgeenvironment_posture_environments'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiopsknowledgeenvironment',
            name='itop_datasource_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='iTop 数据源'),
        ),
        migrations.AddField(
            model_name='aiopsknowledgeenvironment',
            name='zabbix_datasource_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Zabbix 数据源'),
        ),
    ]
