# Generated by Django 5.2.15 on 2026-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0022_add_zabbix_itop_ids_to_knowledge_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiopsknowledgeenvironment',
            name='causal_rule_set',
            field=models.JSONField(blank=True, default=dict, verbose_name='L1因果规则集'),
        ),
    ]
