# Generated by Django 5.2.15 on 2026-09-18 03:06

import sxdevops.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlaudit', '0002_datasource_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='password',
            field=sxdevops.fields.EncryptedCharField(max_length=512, verbose_name='密码'),
        ),
    ]
