# Generated by Django 5.2.15 on 2026-06-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_resourcerequest_approval_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='costrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='citype',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddConstraint(
            model_name='costrecord',
            constraint=models.UniqueConstraint(fields=('ci', 'month'), name='cmdb_costrecord_unique_ci_month'),
        ),
    ]
