# Generated by Django 5.2.15 on 2026-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_citype_updated_at_costrecord_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='iTopDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('api_url', models.CharField(max_length=256, verbose_name='API 地址')),
                ('api_version', models.CharField(default='1.4', max_length=8, verbose_name='API 版本')),
                ('auth_user', models.CharField(max_length=64, verbose_name='用户名')),
                ('auth_password', models.CharField(max_length=256, verbose_name='密码')),
                ('organization', models.CharField(blank=True, max_length=128, verbose_name='组织')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('sync_mode', models.CharField(choices=[('full', '全量'), ('incremental', '增量')], default='full', max_length=16, verbose_name='同步模式')),
                ('sync_interval', models.PositiveIntegerField(default=3600, verbose_name='同步间隔(秒)')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='同步配置')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='上次同步')),
                ('sync_status', models.CharField(default='idle', max_length=16, verbose_name='同步状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'iTop 数据源',
                'verbose_name_plural': 'iTop 数据源',
                'ordering': ['name'],
            },
        ),
    ]
