# Generated by Django 5.2.15 on 2026-07-07 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_itopdatasource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configitem',
            options={'ordering': ['-updated_at', 'name'], 'verbose_name': '配置项', 'verbose_name_plural': '配置项'},
        ),
        migrations.AddField(
            model_name='configitem',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='外部 ID'),
        ),
        migrations.AddField(
            model_name='configitem',
            name='itop_datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_items', to='cmdb.itopdatasource', verbose_name='iTop 数据源'),
        ),
        migrations.AddIndex(
            model_name='configitem',
            index=models.Index(fields=['itop_datasource', 'external_id'], name='cmdb_config_itop_da_db1da5_idx'),
        ),
    ]
