# Generated by Django 5.2.15 on 2026-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_alter_configitem_options_configitem_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itopdatasource',
            name='sync_status',
            field=models.CharField(default='idle', max_length=255, verbose_name='同步状态'),
        ),
    ]
