# Generated by Django 5.2.15 on 2026-09-24 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_alter_itopdatasource_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='citype',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='抽象类型'),
        ),
        migrations.AddField(
            model_name='citype',
            name='layer',
            field=models.PositiveIntegerField(default=0, verbose_name='层级'),
        ),
        migrations.AddField(
            model_name='citype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cmdb.citype', verbose_name='父类型'),
        ),
    ]
