# Generated by Django 5.2.15 on 2026-09-24 04:41

from django.db import migrations, models


def seed_default_relation_types(apps, schema_editor):
    """种入 3 个系统内置类型 + 2 个本体扩展类型（与 models.DEFAULT_RELATION_TYPES 一致）。"""
    RelationType = apps.get_model('cmdb', 'RelationType')
    defaults = [
        {
            'code': 'depends_on', 'name': '业务依赖', 'display_name': '依赖',
            'description': '业务依赖：上游故障影响下游（source impacts target）',
            'color': '#8b5cf6', 'line_style': 'solid', 'direction': 'forward',
            'ontology_property': 'dependsOn', 'is_system': True, 'weight': 10, 'sort_order': 1,
        },
        {
            'code': 'runs_on', 'name': '部署在', 'display_name': '部署在',
            'description': '部署承载关系（软件实例部署于主机/Pod）',
            'color': '#0ea5e9', 'line_style': 'dashed', 'direction': 'forward',
            'ontology_property': 'hostedOn', 'is_system': True, 'weight': 8, 'sort_order': 2,
        },
        {
            'code': 'connects_to', 'name': '连接到', 'display_name': '连接到',
            'description': '网络连接关系（设备接入网络设备）',
            'color': '#94a3b8', 'line_style': 'dotted', 'direction': 'bidirectional',
            'ontology_property': 'connectedTo', 'is_system': True, 'weight': 5, 'sort_order': 3,
        },
        {
            'code': 'hosted_on', 'name': '承载于', 'display_name': '承载于',
            'description': '承载关系（虚拟机/实例承载于宿主或主机）',
            'color': '#0ea5e9', 'line_style': 'dashed', 'direction': 'forward',
            'ontology_property': 'hostedOn', 'is_system': False, 'weight': 7, 'sort_order': 4,
        },
        {
            'code': 'contains', 'name': '包含', 'display_name': '包含',
            'description': '组成包含关系（实例包含表空间、表空间包含数据文件）',
            'color': '#10b981', 'line_style': 'solid', 'direction': 'forward',
            'ontology_property': 'contains', 'is_system': False, 'weight': 7, 'sort_order': 5,
        },
    ]
    for entry in defaults:
        RelationType.objects.get_or_create(code=entry['code'], defaults=entry)


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_citype_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='关系码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='拓扑显示名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#94a3b8', max_length=20, verbose_name='拓扑颜色')),
                ('line_style', models.CharField(choices=[('solid', '实线'), ('dashed', '虚线'), ('dotted', '点线')], default='solid', max_length=10, verbose_name='线型')),
                ('direction', models.CharField(choices=[('forward', '前向（source 影响 target）'), ('reverse', '反向（target 影响 source）'), ('bidirectional', '双向')], default='forward', max_length=16, verbose_name='方向语义')),
                ('allowed_source_types', models.JSONField(blank=True, default=list, verbose_name='允许的源类型')),
                ('allowed_target_types', models.JSONField(blank=True, default=list, verbose_name='允许的目标类型')),
                ('ontology_property', models.CharField(blank=True, default='', max_length=50, verbose_name='本体属性名')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CI 关系类型',
                'verbose_name_plural': 'CI 关系类型',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_default_relation_types, migrations.RunPython.noop),
    ]
