# Generated by Django 5.2.15 on 2026-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0058_zabbixdatasource_alter_hosttask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionticket',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='外部ID'),
        ),
        migrations.AddField(
            model_name='transactionticket',
            name='external_source',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='外部来源'),
        ),
        migrations.AddField(
            model_name='transactionticket',
            name='external_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='外部链接'),
        ),
    ]
