# Generated by Django 5.2.15 on 2026-07-01 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_itopdatasource'),
        ('ops', '0059_transactionticket_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zabbix_hostid', models.CharField(max_length=32, unique=True, verbose_name='Zabbix 主机 ID')),
                ('zabbix_hostname', models.CharField(max_length=128, verbose_name='Zabbix 主机名')),
                ('zabbix_ip', models.CharField(max_length=64, verbose_name='Zabbix IP')),
                ('match_method', models.CharField(choices=[('ip_exact', 'IP 精确匹配'), ('name_fuzzy', '名称模糊匹配'), ('manual', '人工指定')], default='ip_exact', max_length=16, verbose_name='匹配方式')),
                ('match_confidence', models.FloatField(default=1.0, verbose_name='匹配置信度')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已确认')),
                ('last_matched_at', models.DateTimeField(auto_now=True, verbose_name='上次匹配时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zabbix_mapping', to='cmdb.configitem', verbose_name='关联 CI')),
            ],
            options={
                'verbose_name': '设备关联映射',
                'verbose_name_plural': '设备关联映射',
                'indexes': [models.Index(fields=['zabbix_ip'], name='ops_devicem_zabbix__750a30_idx'), models.Index(fields=['config_item'], name='ops_devicem_config__d4d1ff_idx')],
            },
        ),
    ]
