# Generated by Django 5.2.15 on 2026-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0060_devicemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='外部 ID'),
        ),
        migrations.AddField(
            model_name='host',
            name='source',
            field=models.CharField(default='manual', max_length=32, verbose_name='来源'),
        ),
    ]
