# Generated by Django 5.2.15 on 2026-07-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0061_host_external_id_host_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresource',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='外部 ID'),
        ),
        migrations.AddField(
            model_name='taskresource',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_resources', to='ops.host', verbose_name='关联主机'),
        ),
    ]
