# Generated by Django 5.2.15 on 2026-09-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0062_taskresource_external_id_taskresource_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafanasetting',
            name='api_token',
            field=models.CharField(blank=True, default='', help_text='Grafana Service Account Token（glsa_...），服务端调用 Grafana API 使用', max_length=256, verbose_name='API Token'),
        ),
        migrations.AddField(
            model_name='grafanasetting',
            name='jwt_secret',
            field=models.CharField(blank=True, default='', help_text='与 Grafana [auth.jwt] 共享的 HS256 secret，用于签发 iframe 嵌入的 auth_token', max_length=256, verbose_name='JWT Secret'),
        ),
        migrations.AddField(
            model_name='grafanasetting',
            name='org_id',
            field=models.PositiveIntegerField(default=1, help_text='嵌入 URL 的 orgId 参数', verbose_name='Org ID'),
        ),
        migrations.AddField(
            model_name='grafanasetting',
            name='timeout',
            field=models.PositiveIntegerField(default=10, verbose_name='超时(秒)'),
        ),
        migrations.AddField(
            model_name='grafanasetting',
            name='tls_verify',
            field=models.BooleanField(default=True, verbose_name='TLS 验证'),
        ),
    ]
