# Generated by Django 5.2.15 on 2026-09-18 03:06

import sxdevops.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0065_zabbixdatasource_annotation_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerhost',
            name='ssh_password',
            field=sxdevops.fields.EncryptedCharField(blank=True, default='', max_length=256, verbose_name='SSH 密码'),
        ),
        migrations.AlterField(
            model_name='nginxenvironment',
            name='ssh_password',
            field=sxdevops.fields.EncryptedCharField(blank=True, default='', max_length=256, verbose_name='SSH 密码'),
        ),
        migrations.AlterField(
            model_name='taskresource',
            name='ssh_password',
            field=sxdevops.fields.EncryptedCharField(blank=True, default='', max_length=256, verbose_name='SSH 密码'),
        ),
        migrations.AlterField(
            model_name='zabbixdatasource',
            name='password',
            field=sxdevops.fields.EncryptedCharField(blank=True, default='', max_length=256, verbose_name='密码'),
        ),
    ]
