# Generated by Django 5.2.15 on 2026-09-18 03:06

import sxdevops.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0066_alter_dockerhost_ssh_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ssh_password',
            field=sxdevops.fields.EncryptedCharField(blank=True, default='', max_length=256, verbose_name='SSH 密码'),
        ),
    ]
