# Generated by Django 5.2.15 on 2026-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0067_alter_host_ssh_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertintegration',
            name='ai_analysis_enabled',
            field=models.BooleanField(default=True, verbose_name='启用 AI 分析'),
        ),
        migrations.AddField(
            model_name='alertintegration',
            name='ai_analysis_min_level',
            field=models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=16, verbose_name='AI 分析最低级别'),
        ),
    ]
