# Generated by Django 5.2.15 on 2026-09-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0068_alertintegration_ai_analysis_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationrule',
            name='notify_on_aiops_analysis',
            field=models.BooleanField(default=False, verbose_name='AI 分析完成时通知'),
        ),
    ]
