# Generated by Django 5.2.15 on 2026-09-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0069_alertnotificationrule_notify_on_aiops_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='告警码'),
        ),
        migrations.AddField(
            model_name='alert',
            name='causal_level',
            field=models.CharField(choices=[('none', '无'), ('root', '根因'), ('derived', '派生')], db_index=True, default='none', max_length=8, verbose_name='因果层级'),
        ),
        migrations.AddField(
            model_name='alert',
            name='derived_from',
            field=models.JSONField(blank=True, default=list, verbose_name='派生来源'),
        ),
        migrations.AddField(
            model_name='alert',
            name='evidence_chain',
            field=models.JSONField(blank=True, default=list, verbose_name='证据链'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_code', 'status'], name='ops_alert_alert_c_e139d8_idx'),
        ),
    ]
