# Generated by Django 5.2.15 on 2026-09-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0070_alert_causality_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCausalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='规则 ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('source_alert_codes', models.JSONField(blank=True, default=list, verbose_name='前件告警码')),
                ('target_alert_codes', models.JSONField(blank=True, default=list, verbose_name='派生告警码')),
                ('relation_type_code', models.CharField(blank=True, default='', max_length=32, verbose_name='沿用的关系类型码')),
                ('direction', models.CharField(choices=[('upstream', '上溯（沿关系图向根因方向）'), ('downstream', '下溯（沿关系图向影响方向）')], default='upstream', max_length=16, verbose_name='推理方向')),
                ('max_hops', models.PositiveIntegerField(default=5, verbose_name='最大跳数')),
                ('window_minutes', models.PositiveIntegerField(default=5, verbose_name='时间窗(分钟)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('notes', models.TextField(blank=True, verbose_name='备注（F 组安全联动预留语义）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'L1 因果规则',
                'verbose_name_plural': 'L1 因果规则',
                'ordering': ['priority', 'code'],
            },
        ),
    ]
